version: '3.4'

services:
  todo_api:
    build:
      context: ./src/TodoApi
      dockerfile: TodoApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mssql

  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=rootPassword1!
    volumes:
      - mssql_data_container:/data/db_mssql


  ui:
    image: ui:dev
    build:
      dockerfile: Dockerfile
      context: ./src/todo-ui
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      WDS_SOCKET_PORT: 80
    volumes:
      - ./src/todo-ui/src:/app/src
      - ./src/todo-ui/public:/app/public

  server:
    depends_on:
      - todo_api
      - ui
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./src/server
    ports:
      - "80:80"

volumes:
  mssql_data_container: