FROM node:14.14.0-alpine as build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginx as final
COPY ./default.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /var/www/ui